
DATA_PATH = 'data'
ORGAN_NUMBER = 1
FOLDS = 10
LOW_RANGE = -100
HIGH_RANGE = 240


CURRENT_FLOD = 0
SLICE_THRESHOLD = 0.98
SLICE_THICKNESS = 3
ORGAN_ID = 1
GPU_ID = 0
LEARNING_RATE_1 = 1e-5
LEARNING_RATE_m1 = 10
LEARNING_RATE_2 = 1e-5
LEARNING_RATE_m2 = 10
MARGIN = 20
PROB = 0.5
SAMPLE_BATCH = 1
TRAINING_EPCOH_S = 2
TRAINING_EPCOH_I = 6
TRAINING_EPCOH_J = 8
LR_DECAY_EPOCH_J_STEP = 2
